
server:
  port: 8383
spring:

  application:
    name: dev-manager
  datasource:
    type:
      com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.26.47.132:3306/yzbc?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&useJDBCCompliantTimezoneShift=true
    username: robotweb
    password: LG5qnmHfe5KmVDQb
    initialSize: 3
    minidle: 3
    maxActive: 18
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM pic
    filters: stat,wall,log4j
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB

file:
  staticAccessPath: /static/image/**


wx:
  appid: wx91de71c9f31b0def
  appsecret: e2081a9c150fdfe8d5a1a087eed33030




mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
logging:
  level:
    com.bm.coursemanage.dao: debug

image:
  dirpath: "/usr/upload/"
  webpath: "http://120.78.151.130:8383/upload"
